# Site settings
title: Sam Neirinck
header-img: img/home-bg.jpg
email: info@samneirinck.com
description: "Sam Neirinck's blog dump"
url: "http://samneirinck.com"
twitter_username: samneirinck
github_username:  samneirinck
timezone: Europe/Brussels

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
